server:
  port: 5555

  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: rootroot
    key-alias: tomcat

http:
  port: 5556

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/board_of_ads
    username: root
    password: root
    initialization-mode: always

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: false
        jdbc:
          timezone: UTC

  mail:
    host: smtp.yandex.ru
    port: 465
    username: echopride@yandex.ru
    password: terror333
    protocol: smtps
    debug: true

  security:
    require-ssl: true

    oauth2:
      client:
        registration:
          google:
            client-id: 71097759200-4uvk2r27d0dpl6r6hmtvn2ildq1pk229.apps.googleusercontent.com
            client-secret: rf303CdsMzSGtiOMIc3y8w_C
            username: BoardOfAdsProject@gmail.com
            password: Of@ds.2020
          facebook:
            clientId: 3623063611061740
            clientSecret: e9bd600c53c31c81447ab85e7de650e5
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
          resource:
            userInfoUri: https://graph.facebook.com/me?fields=id,first_name,last_name,email

    auth_yandex:
      client_id: 2561bd17ecc1441d9c2461d780690cae
      client_secret: cc96fba5ab674d159b7d191215e1697b
      response_type: code
      display: popup
      redirect_url: http://localhost:5556/social/auth_yandex
      auth_url: https://oauth.yandex.ru/authorize
      token_url: https://oauth.yandex.ru/token
      user_info_url: https://login.yandex.ru/info

    auth_instagram:
      client_id: 649495255959244
      client_secret: 1dfd28b75b9f50202f2ca3e577952af8
      auth_url: https://api.instagram.com/oauth/authorize
      redirect_uri: https://localhost:5555/social/auth_instagram
      token_url: https://api.instagram.com/oauth/access_token
      user_info_url: https://graph.instagram.com/me

    auth_ok:
      client_id: 512000795910
      client_secret: E1F927C4035CFA963D062FE4
      response_type: code
      scope: GET_EMAIL;VALUABLE_ACCESS;LONG_ACCESS_TOKEN;PHOTO_CONTENT;
      grant_type: authorization_code
      redirect_url: http://localhost:5556/social/auth_ok
      auth_url: https://connect.ok.ru/oauth/authorize
      token_url: https://api.ok.ru/oauth/token.do
      user_info_url: http://api.ok.ru/fb.do
      method: users.getCurrentUser
      client_public: CHAGCBKGDIHBABABA
      format: json

    auth-vk:
      client_id: 7604924
      client_secret: acpHC7p5T746jYx17yz1
      response_type: code
      redirect_url: http://localhost:5556/social/auth_vk
      auth_url: http://oauth.vk.com/authorize
      token_url: https://oauth.vk.com/access_token
      users_get_url: https://api.vk.com/method/users.get
      scope: email
      display: popup
      fields: photo_100
      version: 5.124

    auth-mail:
      clientId: 782202
      clientSecret: b9eb215e5bfb9c8d6d7baaf8fc5309ad
      responseType: code
      redirectURL: http://localhost:5556/social/mail_auth
      auth: https://connect.mail.ru/oauth/authorize
      tokenUrl: https://connect.mail.ru/oauth/token
      userInfoUrl: http://www.appsmail.ru/platform/api


  jhipster:
    mail: # specific JHipster mail property, for standard properties see MailProperties
    from: kunaev993@gmail.com
    base-url: http://127.0.0.1:5556

jwt:
  secret: boardofads

yandexMap:
  api-key: c8207e9a-202c-4b74-9711-12c84ec3771f
